basePath: /api/v1/auth
definitions:
  core.Code:
    enum:
    - INVALID_INITDATA
    - INVALID_USER_ID
    - OK
    - INTERNAL_ERROR
    type: string
    x-enum-varnames:
    - CodeInvalidInitData
    - CodeInvalidUserID
    - CodeOK
    - CodeInternal
  core.UserReferrals:
    properties:
      firstname:
        type: string
      referralId:
        type: integer
      username:
        type: string
    type: object
  server.errorResponse:
    properties:
      code:
        $ref: '#/definitions/core.Code'
      errorInfo:
        type: string
    type: object
  server.userInfoResponse:
    properties:
      firstname:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is Auth server.
  title: Game API
  version: "1.0"
paths:
  /api/v1/auth/me:
    get:
      consumes:
      - application/json
      description: Get user data
      parameters:
      - description: InitData header
        in: header
        name: initData
        required: true
        type: string
      - description: get param inviterId
        in: query
        name: inviterId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.userInfoResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.errorResponse'
      summary: Get user data
      tags:
      - Auth
  /api/v1/auth/referrals/{id}:
    get:
      consumes:
      - application/json
      description: Get user referrals
      parameters:
      - description: Inviter Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/core.UserReferrals'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.errorResponse'
      summary: Get user referrals
      tags:
      - Auth
swagger: "2.0"
