basePath: /api/v1/auth
definitions:
  core.Code:
    enum:
    - OK
    - INTERNAL_ERROR
    - INVALID_INITDATA
    - INVALID_USER_ID
    type: string
    x-enum-varnames:
    - CodeOK
    - CodeInternal
    - CodeInvalidInitData
    - CodeInvalidUserID
  core.UserInfo:
    properties:
      firstname:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  server.errorResponse:
    properties:
      code:
        $ref: '#/definitions/core.Code'
      errorInfo:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is Auth server.
  title: Game API
  version: "1.0"
paths:
  /api/v1/auth/me:
    get:
      consumes:
      - application/json
      description: Get user data
      parameters:
      - description: InitData header
        in: header
        name: initData
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.UserInfo'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/server.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.errorResponse'
      summary: Get user data
      tags:
      - Auth
swagger: "2.0"
